language: node_js
node_js:
  - 10.16.3
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f /tmp/terraform.zip
install:
  - pushd src && npm install && popd
jobs:
  include:
    - stage: test
      script: ./test.sh
      env:
        - NODE_ENV=test
        - APP_PORT=8080
    - stage: deploy
      script: ./deploy.sh
env:
  global:
    - secure: th4H+xJ28V1vGHidsInOMAG299DM6dZ7eA1wBYFkeNHevzSjttHrek6aHruzBwFiWL30eEUOfRGkecxqi33IY9azqDoZLWeYMtiRQIueP9DTkShqGHXfeHwN1Lsyqp9kJ9qpl00v9bnjBlI3v+m+nPKQLAV7/ySPUD7DMmDh+XrR3pDRhre0rcHzJp+e5YjrHshRMwzippwKEuNt4txi5xDCB1B1WQ7G2MRbAiI5b/U06Uljyam0McFPC1pHJSrNODdqI+zIFTTPupIEAzKB4Wo2qCm/cJYv5YO72UUxz952xrvt1reICGa65NLo5Iixjzj3mDUBzR0/NBKO3Bb8Eby6QuSTXmWJcGRbzCSjG9mcLOohTbwRpxIEEZePtouNP9q11Bg3NJRF4yvhUiGz3u1N2yDrcW9XRYsHBY/J8+iSPHKVgz8pQmWl6bs6JNSnbcD6+kXhuaLMyhbsTvrDLdnvqodwAaQk+pfoMtNgsZKP5TbOVT2slMUHpRrJWvFyLoHqa+DKMxDPMvdcWO/FpoRmxDsd0fkCsm75owBByljneV3wbMMdkbJ+4TubG+G+aPWeNCV0TrJz9FKad1cJOxtkE0ou1gahQdU7eu7vS1Yf6Q2jHmc7ixreAvVBwKAHNOZfP6ye5ucppYt+vfR2G715WFZ87nMkvb5nCWoCDAI=
    - secure: h1IgqacNM399Kc/7Fa7q3ZRQSD5gGkskEwvsXU/MInAIuOniJCoFnDTP/aPAi8mQj0ct5tN2iQAd10rPl4F2Bwy2U4+PDk9aCFtIKT6rocAnr4PhpXa+3APWhouuJgW0JucJHhEe6mFYFJ2p0NYchKpqDwZp7Qg1BMIWnPgGFGDgjqc17jkwic2IifzLDcAbofe8InX6lGNHS/KsLRq3vR7CC4MmAlzcy976BWi6HKbTAJVtCpKrR5FzP1bu2HyYrWWK0XTOMOEOlpDII8GAQxf6k8mwxWbGGIa2zY08tRfwW5cmF+JfGWKp9rsRMdV8nx6zIPexjTnSVbKySCxeOLK/NJCHjFIOUAx8lYQHI3lbIxyyWFLFtln+9T3AyU7j7z4T+MasoTnrvJWMjpdg7zWUplJSbuKzw5lmBbkE/EbBmp2FIB60OwoKj8f6rZ0RLZkS01+zo8jWZs4aJYnlbruyiY3HXazd9KjrwjLH3PeX9290olPVuoFVA05OGBrj9PN1Vp26qsaDgCGkvR3qQxhpEjItVIFfeYHFB6l1k3LC6x2cR9NihT350qCGuVVAeW3yTJy5vwr2MQA8pI/2Ng+PSCSRUDLFbyZFFq+FZPWEmmTy/+JuXU3xI7PCzIj/eRuVeID0r2vmvBovNuzoL+IDmy52jojw/WwNNTjUeR0=
