language: node_js
node_js:
  - 10.16.3
install:
  - npm install
jobs:
  include:
    - stage: "test"
      name: "unit tests"
      script: "cd src && npm run test"
      env:
        - NODE_ENV=TEST
        - APP_PORT=8080
